# Site
repository: linusfoo.github.io

# Content configuration version
version: 2

# Personal info
name: Linus Foo
title: Full Stack Developer, NLP Enthusiast
email: t.e.l.foo@sms.ed.ac.uk
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  linusfoo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: linus-foo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# # Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profilepic.jpg
about_content: I am an AI Engineer at Defence Science and Technology Agency (DSTA) working on various fields in Machine Learning including Natural Language Processing (NLP, Automatic Speech Recognition (ASR) and Computer Vision (CV). On the side, I engage in research relating to NLP where my research interest include [Low-resource Languages](https://arxiv.org/abs/2006.07264), [Language Representation](https://aclanthology.org/J19-2006/) and [Biases in LLMs](https://arxiv.org/abs/2309.00770).

  # Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  # You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
  #   - Lists
  #   - Tables
  #   - <a href="google.com">Links</a>
  #   - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:

  - title: Research Publication 
    layout: text
    content: | # this will include new lines to allow paragraphs
     - <h2><strong> Disentangling singlish discourse particles with task-driven representation </strong></h2> <br/> `Abstract:` Singlish, or formally Colloquial Singapore English, is an English-based creole language originating from the SouthEast Asian country Singapore. The language contains influences from Sinitic languages such as Chinese dialects, Malay, Tamil and so forth. A fundamental task to understanding Singlish is to first understand the pragmatic functions of its discourse particles, upon which Singlish relies heavily to convey meaning. This work offers a preliminary effort to disentangle the Singlish discourse particles (lah, meh and hor) with task-driven representation learning. After disentanglement, we cluster these discourse particles to differentiate their pragmatic functions, and perform Singlish-to-English machine translation. Our work provides a computational method to understanding Singlish discourse particles, and opens avenues towards a deeper comprehension of the language and its usage. <br/>  <br/> Full paper available [here](https://dl.acm.org/doi/full/10.1145/3700410.3702117)
     - <h2><strong> Stylistic Evolution and LLM Neutrality in Singlish Language </strong></h2> <br/> `Abstract:` Singlish is a creole rooted in Singapore's multilingual environment and continues to evolve alongside social and technological change. This study investigates the evolution of Singlish over a decade of informal digital text messages. We propose a stylistic similarity framework that compares lexico-structural, pragmatic, psycholinguistic, and encoder-derived features across years to quantify temporal variation. Our analysis reveals notable diachronic changes in tone, expressivity and sentence construction over the years. Conversely, while some LLMs were able to generate superficially realistic Singlish messages, they do not produce temporally neutral outputs, and residual temporal signals remain detectable despite prompting and fine-tuning. Our findings highlight the dynamic evolution of Singlish, as well as the capabilities and limitations of current LLMs in modeling sociolectal and temporal variations in the colloquial language. <br/> <br/> Preprint available [here](https://www.arxiv.org/abs/2601.06580)
  # - title: Research Publication # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       content: [Preprint](https://arxiv.org/abs/2409.20366)
  #       title: M3Oriental @ ACM MMAsia2024
  #       # link: https://arxiv.org/abs/2409.20366
  #       link_text: Preprint
  #       # link_text: Preprint
  #       # additional_links:
  #       #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #       #     icon: fab fa-github
  #       #     url: https://github.com/EMZEDI/Happify (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       #   # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       # quote: >
  #       #   Disentangling singlish discourse particles with task-driven representation
  #       description: <h2> Disentangling singlish discourse particles with task-driven representation </h2>  <br/> `
  #       # description: <h2> Disentangling singlish discourse particles with task-driven representation </h2>  <br/> abstract: Singlish, or formally Colloquial Singapore English, is an English-based creole language originating from the SouthEast Asian country Singapore. The language contains influences from Sinitic languages such as Chinese dialects, Malay, Tamil and so forth. A fundamental task to understanding Singlish is to first understand the pragmatic functions of its discourse particles, upon which Singlish relies heavily to convey meaning. This work offers a preliminary effort to disentangle the Singlish discourse particles (lah, meh and hor) with task-driven representation learning. After disentanglement, we cluster these discourse particles to differentiate their pragmatic functions, and perform Singlish-to-English machine translation. Our work provides a computational method to understanding Singlish discourse particles, and opens avenues towards a deeper comprehension of the language and its usage.
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Defence Science and Technology Agency (DSTA)
        sub_title: Software Engineer
        caption: Sept 2024 - Present
        # link: Link to company (optional)
        # quote: >
        #   Short description of the company (optional)
        description: | 
          - Developing AI models in speech and computer vision, with a focus on low-resource languages and environments.
          - Building backend systems, leveraging technologies such as Kafka for real-time data streaming and processing.
          - Working at the intersection of AI and infrastructure to create scalable, efficient, and high-performance solutions.
          - Developing responsive, user-friendly user-interface for web applications.
    # layout: list
    # content:
      - layout: left
        title: Elettronica Group
        sub_title: AI Engineer (Intern)
        caption: June 2023 ‑ Aug 2023
        # link: Link to company (optional)
        # quote: >
        #   Short description of the company (optional)
        description: | 
          - Selected as part of a Global Internship Program that allows students to work in relevant companies worldwide.
          - Developed methodologies to improve on both visible and infrared drone‑detection technologies using various Computer Vision Models.
    # layout: list
    # content:
      - layout: left
        title: Defence Science and Technology Agency (DSTA)
        sub_title: AI Engineer (Intern)
        caption: > 
          May 2022 ‑ Aug 2022
        # link: Link to company (optional)
        # quote: >
        #   Short description of the company (optional)
        description: |
          - Worked with generative LLMs (such as GPT-models) to perform translation of low-resource languages.
        
  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Edinburgh 
        sub_title: MSc in Speech and Language Processing
        caption: 2023-2024
        description: | 
          - Awarded Grade: Distinction 
          - Dissertation Topic: [Towards Representational Learning of Pragmatic Functions of Singlish Discourse Particles Using LLMs](https://drive.google.com/file/d/1p8w4F9UfFZLsQzOBOybKx4mMlE7TCTjH/view?usp=sharing)
          - Relevant Classes:
            - Accelerated Natural Language Processing 
            - Speech Processing 
            - Natural Language Understanding, Generation, and Machine Translation 
            - Automatic Speech Recognition 
            - Reinforcement Learning 
      - layout: left
        title: McGill University
        sub_title: Bsc in Computer Science, Minor in Mathematics
        caption: 2020-2023
        # quote: >
        #   One of the 
        description: | 
          - GPA 3.93/4.0
          - Relevant Classes:
            - Applied Machine Learning
            - Computational Linguistics
            - Probabilitis Programming
            - NLP and Data Science
        # - Accelerated Natural Language Processing 
        # - Speech Processing 
        # - Natural Language Understanding, Generation, and Machine Translation 
        # - Automatic Speech Recognition 
        # - Reinforcement Learning 
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Happify.AI
        link: https://github.com/EMZEDI/Happify
        link_text: A Smart Radio
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/EMZEDI/Happify (eg. sproogen.github.io/modern-resume-theme)(optional)
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          A smart radio that uses facial recognition technology to predict user's emotion to modify their song playlist.
        description: Used Deep Face and Dlib models to predict emotions and fatigue level of users based on their facial expression. The system enqueues songs based on predictions using algorithm which ensures a smooth transition between songs based on their characteristics (tempo, danceability etc.) obtained using Spotipy to optimize user's mood and focus level. # this will include new lines to allow paragraphs | 
      
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      On top of the really exciting and nerdy stuff that I do at work, I am also a competitive multisport (duathlons and triathlons) athlete.
      Here are some pictures of me in action:
      
      ![alt text](/images/IMG_9354.jpg "Cycling"){: width="30%"} ![alt text](/images/123838.jpeg "running"){: width="30%"}

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
